//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsientoEspejo.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsientoEspejo.App_GlobalResources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /* Select From [DBO].[OJDT] M0 */
        ///Declare @FechaIni As DateTime
        ///Declare @FechaFin As DateTime
        ////* WHERE */
        ///Set DateFormat DMY
        ///Set @FechaIni =getdate()-90
        ///Set @FechaFin =&apos;31-12-2030&apos; 
        ///Select Distinct Top 1 &apos;JOUR&apos; As &apos;Indicador&apos;, A2.U_IdIntegra, A0.DocDate As &apos;RefDate&apos;, A0.TaxDate As &apos;TaxDate&apos;, A0.DocDueDate As &apos;DueDate&apos;, 
        ///cast(A0. DocNum as nvarchar) As &apos;Ref1&apos;, &apos;&apos; As &apos;Ref2&apos;, A0.JrnlMemo As &apos;Memo&apos;, &apos;I&apos; As &apos;U_OK1_IFRS&apos;, A0.CardCode, 
        ///cast(A3.TransId as nvarchar) &apos;TransId&apos;, Cast(A0.DocTotal/A4.DocTotal  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Cab_NC {
            get {
                return ResourceManager.GetString("Cab_NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime Declare @FechaFin As DateTime Set DateFormat DMY 
        ///Set @FechaIni = getdate()-90 Set @FechaFin = &apos;31-12-2030&apos; 
        ///SELECT Distinct T0.series,T0.refdate&apos;refdate&apos;, T0.DueDate,T0.TaxDate,T0.Memo,T0.ref1,t0.ref2,T0.ref3,T0.Project,
        ///T0.TransCode, cast(T1.TransID as nvarchar) &apos;TransID&apos;,T1.Baseref
        ///FROM OJDT T0 Inner JOIN JDT1 T1 ON T0.TransId=T1.TransId INNER JOIN OACT T2 
        ///ON T1.[Account] = T2.[AcctCode] WHERE T0.RefDate &gt; @FechaIni and T0.BaseRef=&apos;%0%&apos; And T0.CreatedBy =&apos;%1%&apos; .
        /// </summary>
        public static string cabecera {
            get {
                return ResourceManager.GetString("cabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime Declare @FechaFin As DateTime Set DateFormat DMY 
        ///Set @FechaIni = getdate()-45 
        ///SELECT Distinct T0.series,T0.refdate,T0.DueDate,T0.TaxDate,T0.Memo,T0.ref1,t0.ref2,T0.ref3,T0.Project,
        ///T0.TransCode, cast(T1.TransID as nvarchar) &apos;TransID&apos;,T1.Baseref
        ///FROM OJDT T0 Inner JOIN JDT1 T1 ON T0.TransId=T1.TransId INNER JOIN OACT T2 
        ///ON T1.[Account] = T2.[AcctCode] WHERE T0.RefDate &gt; @FechaIni  and T0.BaseRef=&apos;%0%&apos; And T0.TransID =&apos;%1%&apos;.
        /// </summary>
        public static string Cabecera_Pagos_Efec {
            get {
                return ResourceManager.GetString("Cabecera_Pagos_Efec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime Declare @FechaFin As DateTime Set DateFormat DMY 
        ///Set @FechaIni = getdate()-95 Set @FechaFin = &apos;31-12-2030&apos; 
        ///SELECT Distinct T0.series,T0.refdate,T0.DueDate,T0.TaxDate,T0.Memo,T0.ref1,t0.ref2,T0.ref3,T0.Project,
        ///T0.TransCode, cast(T1.TransID as nvarchar) &apos;TransID&apos;,T1.Baseref
        ///FROM OJDT T0 Inner JOIN JDT1 T1 ON T0.TransId=T1.TransId INNER JOIN OACT T2 
        ///ON T1.[Account] = T2.[AcctCode] WHERE T0.RefDate &gt;@FechaIni and T0.TransId=&apos;%0%&apos; .
        /// </summary>
        public static string CabeceraAsientosManuales {
            get {
                return ResourceManager.GetString("CabeceraAsientosManuales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime Declare @FechaFin As DateTime Set DateFormat DMY 
        ///Set @FechaIni = getdate()-45 Set @FechaFin = &apos;31-12-2030&apos; 
        ///SELECT Distinct T0.series,T0.refdate,T0.DueDate,T0.TaxDate,T0.Memo,T0.ref1,t0.ref2,T0.ref3,T0.Project,
        ///T0.TransCode, cast(T1.TransID as nvarchar) &apos;TransID&apos;,T1.Baseref,t3.CardCode
        ///FROM OJDT T0 Inner JOIN JDT1 T1 ON T0.TransId=T1.TransId INNER JOIN OACT T2 
        ///ON T1.[Account] = T2.[AcctCode] Inner JOin ORCT t3 on t3.DocEntry=&apos;%0%&apos; WHERE T0.RefDate &gt; @FechaIni and T0.Base [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string CabeceraRecibosPago {
            get {
                return ResourceManager.GetString("CabeceraRecibosPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime Declare @FechaFin As DateTime Set DateFormat DMY 
        ///Set @FechaIni = getdate()-45 Set @FechaFin = &apos;31-12-2030&apos; 
        ///SELECT Distinct T0.series,T0.refdate,T0.DueDate,T0.TaxDate,T0.Memo,T0.ref1,t0.ref2,T0.ref3,T0.Project,
        ///T0.TransCode, cast(T1.TransID as nvarchar) &apos;TransID&apos;,T1.Baseref,t3.CardCode
        ///FROM OJDT T0 Inner JOIN JDT1 T1 ON T0.TransId=T1.TransId INNER JOIN OACT T2 
        ///ON T1.[Account] = T2.[AcctCode] Inner JOin ORCT t3 on t3.DocEntry=&apos;%0%&apos; WHERE T0.RefDate &gt; @FechaIni and T0.Base [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string CabeceraRecibosPagoCancelados {
            get {
                return ResourceManager.GetString("CabeceraRecibosPagoCancelados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT count(code) as &apos;nro&apos; FROM [dbo].[@ASIENTOS_LOG_ERROR]  T0.
        /// </summary>
        public static string conse_log {
            get {
                return ResourceManager.GetString("conse_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME=&apos;%0%&apos;.
        /// </summary>
        public static string consl_table {
            get {
                return ResourceManager.GetString("consl_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * 
        ///FROM INFORMATION_SCHEMA.COLUMNS 
        ///WHERE COLUMN_NAME = &apos;%0%&apos; and TABLE_NAME=&apos;%1%&apos;.
        /// </summary>
        public static string consl_table_campo {
            get {
                return ResourceManager.GetString("consl_table_campo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime
        ///Declare @FechaFin As DateTime
        ///Set DateFormat DMY
        ///Set @FechaIni = getdate()-95
        ///Set @FechaFin = &apos;31-12-2030&apos;
        ///Select *
        ///From
        ///(
        ///	Select &apos;01 - Factura de Venta&apos; &apos;Tipo&apos;, B0.DocEntry, B0.DocNum, B0.DocDate, B0.TransId_2doAsiento, B0.U_EsIndep  
        ///	From
        ///	( 
        ///		Select A0.DocEntry, A0.DocNum, A0.DocDate, A0.TransId &apos;TransId_1erAsiento&apos;, A0.Comments, A1.LineNum, A2.TransId &apos;TransId_2doAsiento&apos;, A1.Project, A0.U_EsIndep 
        ///		From OINV A0
        ///		Inner Join INV1 A1 On A0.DocEntry = A1.DocE [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string doc_pendientes {
            get {
                return ResourceManager.GetString("doc_pendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime
        ///Declare @FechaFin As DateTime
        ///Set DateFormat DMY
        ///Set @FechaIni = getdate()-60
        ///Set @FechaFin = &apos;31-12-2030&apos;
        ///Select *
        ///From
        ///(
        ///	Select 
        ///	Case When B0.DocSubType = &apos;--&apos; Then &apos;06 - Factura de Proveedor&apos; Else &apos;06 - Nota Débito de Proveedor&apos; End &apos;Tipo&apos;, 
        ///	B0.DocEntry, B0.DocNum, B0.DocDate, B0.TransId_2doAsiento, B0.U_EsIndep 
        ///	From
        ///	( 
        ///		Select A0.DocEntry, A0.DocNum, A0.DocDate, A0.TransId &apos;TransId_1erAsiento&apos;, A0.Comments, A1.TransId &apos;TransId_2doAsiento&apos;, A0.U_EsIndep,  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Doc_Pendientes_FacCompra {
            get {
                return ResourceManager.GetString("Doc_Pendientes_FacCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select count(*) &apos;cant&apos;
        ///From OINV j0
        ///inner join inv1 j1 on j0.docentry=j1.docentry
        ///inner join ORDR j2 on j1.baseref=j2.Docentry
        ///Where j0.DocEntry=&apos;%0%&apos;.
        /// </summary>
        public static string FactCantLineasSinPedido {
            get {
                return ResourceManager.GetString("FactCantLineasSinPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime 
        ///Declare @FechaFin As DateTime 
        ///Set DateFormat DMY 
        ///Set @FechaIni = getdate()-60
        ///Set @FechaFin = &apos;31-12-2030&apos; 
        ///select aa.Line_ID,aa.shortname,aa.acctcode,aa.U_CTA_IFRS, aa.Debit,Credit,
        ////*case when isnull(aa.U_InfoCo01,&apos;&apos;)=&apos;&apos; then t3.cardcode else aa.U_InfoCo01 end &apos;U_InfoCo01&apos;, se ajusta para mostrar clientes en cuentas 138020*/
        ///case when isnull(aa.U_InfoCo01,&apos;&apos;)=&apos;&apos; then (case when aa.U_CTA_IFRS like (&apos;138020%&apos;) then replace(t3.cardcode,&apos;p&apos;,&apos;C&apos;) else t3.cardcode end) 
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Lin_Fac_Compra {
            get {
                return ResourceManager.GetString("Lin_Fac_Compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select &apos;LINJOUR&apos; As &apos;Indicador&apos;, case when A1.Account=&apos;41552101R&apos; then &apos;41602101R&apos;  
        ///when A1.Account=&apos;41552201R&apos; then &apos;41602201R&apos;
        ///when A1.Account=&apos;41559603R&apos; then &apos;41609603R&apos; 
        ///when A1.Account=&apos;41559604R&apos; then &apos;41609604R&apos; 
        ///when A1.Account=&apos;41559701R&apos; then &apos;41609701R&apos; 
        ///when A1.Account=&apos;41559702R&apos; then &apos;41609702R&apos; 
        ///when A1.Account=&apos;41559703R&apos; then &apos;41609703R&apos; 
        ///when A1.Account=&apos;41561501R&apos; then &apos;41601501R&apos; 
        ///when A1.Account=&apos;41561601R&apos; then &apos;41601601R&apos; 
        ///when A1.Account=&apos;41561603R&apos; then &apos;41601603R&apos; 
        ///when [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Lin_NC {
            get {
                return ResourceManager.GetString("Lin_NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select &apos;LINJOUR&apos; As &apos;Indicador&apos;, A1.Account As &apos;U_AcctCode&apos;, A1.ShortName As &apos;CardCode&apos;, 
        ///Cast(A1.Debit * replace(&apos;%1%&apos;,&apos;,&apos;,&apos;.&apos;) As Numeric(19, 2)) As &apos;U_Credit&apos;, 
        ///Cast(A1.Credit * replace(&apos;%1%&apos;,&apos;,&apos;,&apos;.&apos;) As Numeric(19,2)) As &apos;U_Debit&apos;, 
        ///A1.Project, A1.ProfitCode, A1. U_Concepto ,A2.CardCode &apos;U_InfoCo01&apos; 
        ///From OJDT A0
        ///Inner Join JDT1 A1 On A0.TransId = A1.TransId 
        ///inner join OCRD A2 On replace(replace(replace(A0.Memo,&apos;Facturas clientes - &apos;,&apos;&apos;),&apos;A/R Invoices - &apos;,&apos;&apos;),&apos;Notas de crédito clientes - &apos;,&apos;&apos;)=A2 [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Lin_NC_Pend {
            get {
                return ResourceManager.GetString("Lin_NC_Pend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime 
        ///Declare @FechaFin As DateTime 
        ///Set DateFormat DMY 
        ///Set @FechaIni = getdate()-60
        ///Set @FechaFin = &apos;31-12-2030&apos; 
        ///select aa.Line_ID,aa.shortname,aa.acctcode,aa.U_CTA_IFRS, aa.Debit,Credit,
        ///case when isnull(aa.U_InfoCo01,&apos;&apos;)=&apos;&apos; then t3.cardcode else aa.U_InfoCo01 end &apos;U_InfoCo01&apos;,
        ///aa.Project,aa.LineMemo,aa.b,t3.CardCode 
        ///from (
        ///	SELECT T1.Line_ID,T1.shortname,t2.acctcode,T2.U_CTA_IFRS, T1.Debit,Credit,T1.U_InfoCo01,
        ///	T1.Project,T1.LineMemo, 
        ///	  replace(	
        ///		replace(
        ///		  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string lineas {
            get {
                return ResourceManager.GetString("lineas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime Declare @FechaFin As DateTime Set DateFormat DMY 
        ///Set @FechaIni = getdate()-95 Set @FechaFin = &apos;31-12-2030&apos; 
        ///SELECT T1.Line_ID,T1.shortname,t2.acctcode,T2.U_CTA_IFRS, T1.Debit,Credit,T1.U_InfoCo01,
        ///T1.Project,T1.LineMemo,t1.profitcode &apos;Norma_Reparto&apos;,t1.OcrCode2 &apos;Norma_Reparto2&apos; 
        ///FROM OJDT T0 Inner JOIN JDT1 T1 ON T0.TransId=T1.TransId INNER JOIN OACT T2 
        ///ON T1.[Account] = T2.[AcctCode] WHERE T0.RefDate &gt;@FechaIni and T0.TransId=&apos;%2%&apos;.
        /// </summary>
        public static string LineasAsientosManuales {
            get {
                return ResourceManager.GetString("LineasAsientosManuales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select &apos;LINJOUR&apos; As &apos;Indicador&apos;, P0.U_AcctCode, Case When P1.LocManTran = &apos;Y&apos; Then P0.CardCode Else P0.U_AcctCode End CardCode, P0.U_Concepto, P0.U_Debit, P0.U_Credit, IsNull(P0.Project,&apos;&apos;)Project, IsNull(P0.U_ProfitCode,&apos;&apos;)ProfitCode
        ///			From (
        ///				Select A2.U_AcctCode, A2.U_AcctCode As &apos;CardCode&apos;, A2.U_Concepto, IsNUll(A2.U_Debit,0) &apos;U_Debit&apos;, IsNull(A2.U_Credit,0) &apos;U_Credit&apos;, A1.Project, A2.U_ProfitCode
        ///				From OINV A0
        ///				Inner Join INV1 A1 On A0.DocEntry = A1.DocEntry
        ///				Inner Join [@ACS_ASIENTOS [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string lineasfac {
            get {
                return ResourceManager.GetString("lineasfac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select P0.num,&apos;LINJOUR&apos; As &apos;Indicador&apos;, P0.U_AcctCode, Case When P1.LocManTran = &apos;Y&apos; Then P0.CardCode Else P0.U_AcctCode End CardCode, P0.U_Concepto, P0.U_Debit, P0.U_Credit, 
        ///IsNull(P0.Project,&apos;&apos;)Project, IsNull(P0.U_ProfitCode,&apos;&apos;)ProfitCode,P0.InfoCo01,&apos;&apos; &apos;LineMemo&apos;
        ///			From (
        ///				Select 1 &apos;num&apos;,A2.U_AcctCode, A2.U_AcctCode As &apos;CardCode&apos;, A2.U_Concepto, IsNUll(A2.U_Debit,0) &apos;U_Debit&apos;, IsNull(A2.U_Credit,0) &apos;U_Credit&apos;, 
        ///				A1.Project, A2.U_ProfitCode,A0.cardcode &apos;InfoCo01&apos;
        ///				From OINV A0
        ///				Inner  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string lineasfac2 {
            get {
                return ResourceManager.GetString("lineasfac2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime
        ///Declare @FechaFin As DateTime
        ///Set DateFormat DMY
        ///Set @FechaIni =getdate()-95
        ///Set @FechaFin = &apos;31-12-2030&apos;
        ///
        ///Select *
        ///From
        ///(
        ///
        ///
        ///	Select &apos;02 - Nota Crédito Clientes&apos; &apos;Tipo&apos;, B0.DocEntry, B0.DocNum, B0.DocDate, B0.TransId_2doAsiento, B0.U_EsIndep ,b0.ItemCode1
        ///	From
        ///	( 
        ///		Select A0.DocEntry, A0.DocNum, A0.DocDate, A0.TransId &apos;TransId_1erAsiento&apos;, A0.Comments, A1.LineNum, A2.TransId &apos;TransId_2doAsiento&apos;, A1.Project, A0.U_EsIndep, 
        ///		(select count(*) from rin1 J0 where  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string NC_Pendientes {
            get {
                return ResourceManager.GetString("NC_Pendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime
        ///Declare @FechaFin As DateTime
        ///Set DateFormat DMY
        ///Set @FechaIni = getdate()-45
        ///Set @FechaFin = &apos;31-12-2030&apos;
        ///Select *
        ///From
        ///(
        ///	Select &apos;08 - Pagos Efectuados&apos; &apos;Tipo&apos;, B0.DocEntry, B0.DocNum, B0.DocDate, B0.TransId_2doAsiento, B0.U_OK1_IFRS ,b0.TransId_1erAsiento
        ///	From
        ///	( 
        ///		select J0.DocEntry, J0.docnum, J0.DocDate,j1.TransId &apos;TransId_1erAsiento&apos;,J0.Comments,j2.TransId &apos;TransId_2doAsiento&apos;,J0.U_OK1_IFRS, 
        ///		J1.Memo  
        ///		from OVPM J0
        ///		left join OJDT J1 On J0.DocNum=j1. [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Pagos_Efec_Pendientes {
            get {
                return ResourceManager.GetString("Pagos_Efec_Pendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declare @FechaIni As DateTime
        ///Declare @FechaFin As DateTime
        ///Set DateFormat DMY
        ///Set @FechaIni = getdate()-45
        ///Set @FechaFin = &apos;31-12-2030&apos;
        ///Select *
        ///From
        ///(
        ///	Select &apos;03 - Pagos Recibidos&apos; &apos;Tipo&apos;, B0.DocEntry, B0.DocNum, B0.DocDate, B0.TransId_2doAsiento, B0.U_OK1_IFRS ,b0.TransId_1erAsiento
        ///	From
        ///	( 
        ///		select J0.DocEntry, J0.docnum, J0.DocDate,j1.TransId &apos;TransId_1erAsiento&apos;,J0.Comments,j2.TransId &apos;TransId_2doAsiento&apos;,J0.U_OK1_IFRS, 
        ///		J1.Memo  
        ///		from ORCT J0
        ///		left join OJDT J1 On J0.DocNum=j1.B [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Pagos_Rec_Pendientes {
            get {
                return ResourceManager.GetString("Pagos_Rec_Pendientes", resourceCulture);
            }
        }
    }
}
